### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by naomimaki** [naomimaki/furima_28745#12]
フリマアプリの挙動確認をお願いいたします！
以下参照願います。
■https://furima-28745.herokuapp.com/
■Basic認証→ ID: admin PASS: 2222
■出品者用アカウント→　アドレス:c@c / パスワード: 123456qwe 
■購入者用アカウント→　アドレス:f@f / パスワード: 123456qwe 
■購入用カード情報→　カード番号：4242424242424242（16桁）
　　　　　　　　　　　CVC: 123 
                                         有効期限: 1-23

**Comment by tec-camp** [comment]
naomimaki さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by naomimaki** [comment]
完了報告受、クローズ
